add final diff

diff --git a/.github/actions/run_sycl_cts/action.yml b/.github/actions/run_sycl_cts/action.yml
--- a/.github/actions/run_sycl_cts/action.yml
+++ b/.github/actions/run_sycl_cts/action.yml
@@ -68,7 +68,8 @@ runs:
       env:
         PREPEND_PATH: ''  # TODO: have qemu as input and set up this
         SYCL_CTS_TIMEOUT: '02:00:00'
-        SYCL_CTS_FILTER: ''  # TODO: needed?
+        SYCL_CTS_FILTER: ''  # TODO: needed? Is this effectively INCLUSIONS (when all build) ??
+        CTS_CSV_FILE: $GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv
       run: |
         pwd && ls -laR && sleep 2
         echo running sycl cts
@@ -85,13 +86,13 @@ runs:
           -b SYCL-CTS/bin \
           -L SYCL-CTS/lib \
           -e OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so \
-          -s "$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv" \
+          -s "$CTS_CSV_FILE" \
           -l SYCL-CTS/cts.log -f SYCL-CTS/cts.fail \
           -r SYCL-CTS/cts.xml \
           -v \
           $SYCL_CTS_FILTER || exitcode=$?
         export OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so
-        #$GITHUB_WORKSPACE/scripts/create_sycl_cts_test_lists.sh $[[ inputs.prepend_path ]] SYCL-CTS "$CTS_CSV_FILE" csv.txt cts_all.txt
+        $GITHUB_WORKSPACE/.github/scripts/create_sycl_cts_test_lists.sh $PREPEND_PATH SYCL-CTS "$CTS_CSV_FILE" csv.txt cts_all.txt
         # output a diff of the generated list csv.txt and cts_all.txt
-        # - diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
+        diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
         exit $exitcode
