reformat after linting

diff --git a/.github/actions/run_sycl_cts/action.yml b/.github/actions/run_sycl_cts/action.yml
--- a/.github/actions/run_sycl_cts/action.yml
+++ b/.github/actions/run_sycl_cts/action.yml
@@ -12,7 +12,7 @@ runs:
       id: calc_vars
       uses: ./.github/actions/calc_vars
       with:
-        target: ${{ inputs.target }}  
+        target: ${{ inputs.target }}
 
     - name: Install Ninja
       uses: llvm/actions/install-ninja@main
@@ -35,7 +35,16 @@ runs:
         name: dpcpp_${{inputs.target}}
         path: install_dpcpp
 
-  #TODO: unpackage dpcpp *****************************************`
+    - name: unpackage artifacts  # package/unpackage avoids known 'permissions loss' issue
+      shell: bash
+      run: |
+        cd install_dpcpp
+        echo LISTING
+        ls -la
+        tar xf dpcpp.tar
+        rm dpcpp.tar
+        echo LISTING
+        ls -la
 
     - name: run sycl cts
       shell: bash
@@ -46,20 +55,20 @@ runs:
         export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install_dpcpp/lib:$GITHUB_WORKSPACE/install_ock/lib
         export ONEAPI_DEVICE_SELECTOR=opencl:0
         python $GITHUB_WORKSPACE/scripts/testing/run_cities.py \
-        --color=always \
-        --timeout $SYCL_CTS_TIMEOUT \
-        $PREPEND_PATH \
-        -p sycl_cts \
-        -b SYCL-CTS/bin \
-        -L SYCL-CTS/lib \
-        -e OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so \
-        -s "$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv" \
-        -l SYCL-CTS/cts.log -f SYCL-CTS/cts.fail \
-        -r SYCL-CTS/cts.xml \
-        -v \
-        $SYCL_CTS_FILTER || exitcode=$?
+          --color=always \
+          --timeout $SYCL_CTS_TIMEOUT \
+          $PREPEND_PATH \
+          -p sycl_cts \
+          -b SYCL-CTS/bin \
+          -L SYCL-CTS/lib \
+          -e OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so \
+          -s "$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv" \
+          -l SYCL-CTS/cts.log -f SYCL-CTS/cts.fail \
+          -r SYCL-CTS/cts.xml \
+          -v \
+          $SYCL_CTS_FILTER || exitcode=$?
         export OCL_ICD_FILENAMES=$CA_INSTALL_DIR/lib/libCL.so
-       #$GITHUB_WORKSPACE/scripts/create_sycl_cts_test_lists.sh $[[ inputs.prepend_path ]] SYCL-CTS "$CTS_CSV_FILE" csv.txt cts_all.txt
-       # output a diff of the generated list csv.txt and cts_all.txt
-       # - diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
-       exit $exitcode
+        #$GITHUB_WORKSPACE/scripts/create_sycl_cts_test_lists.sh $[[ inputs.prepend_path ]] SYCL-CTS "$CTS_CSV_FILE" csv.txt cts_all.txt
+        # output a diff of the generated list csv.txt and cts_all.txt
+        # - diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
+        exit $exitcode
