Tidy for review (part 2)

diff --git a/.github/actions/run_sycl_cts/action.yml b/.github/actions/run_sycl_cts/action.yml
--- a/.github/actions/run_sycl_cts/action.yml
+++ b/.github/actions/run_sycl_cts/action.yml
@@ -39,12 +39,8 @@ runs:
       shell: bash
       run: |
         cd SYCL-CTS
-        echo LISTING
-        ls -la
         tar xf sycl-cts.tar
         rm sycl-cts.tar
-        echo LISTING
-        ls -la
 
     - name: download dpc++ artifact
       uses: actions/download-artifact@v4
@@ -56,27 +52,20 @@ runs:
       shell: bash
       run: |
         cd install_dpcpp
-        echo LISTING
-        ls -la
         tar xf dpcpp.tar
         rm dpcpp.tar
-        echo LISTING
-        ls -la
 
     - name: run sycl cts
       shell: bash
       env:
         PREPEND_PATH: ''  # TODO: have qemu as input and set up this
         SYCL_CTS_TIMEOUT: '02:00:00'
-        SYCL_CTS_FILTER: ''  # TODO: needed? Is this effectively INCLUSIONS (when all build) ??
+        SYCL_CTS_FILTER: ''
       run: |
-        pwd && ls -laR && sleep 2
         echo running sycl cts
         export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install_dpcpp/lib:$GITHUB_WORKSPACE/install_ock/lib
         export ONEAPI_DEVICE_SELECTOR=opencl:0
-        export CTS_CSV_FILE=$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv # can't set in env:
-        # TODO: assume sycl-cts.csv is a new file?
-        #       SYCL-CTS/lib does not exist?
+        export CTS_CSV_FILE=$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv
         set -x
         python $GITHUB_WORKSPACE/scripts/testing/run_cities.py \
           --color=always \
@@ -91,9 +80,8 @@ runs:
           -r SYCL-CTS/cts.xml \
           -v \
           $SYCL_CTS_FILTER || exitcode=$?
-        # TODO: Restore the following shell script - appears to need runs including ALL test categories
-        #export OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so
-        #$GITHUB_WORKSPACE/.github/scripts/create_sycl_cts_test_lists.sh $PREPEND_PATH SYCL-CTS $CTS_CSV_FILE csv.txt cts_all.txt
-        ## output a diff of the generated list csv.txt and cts_all.txt
-        #diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
+        export OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so
+        $GITHUB_WORKSPACE/.github/scripts/create_sycl_cts_test_lists.sh $PREPEND_PATH SYCL-CTS $CTS_CSV_FILE csv.txt cts_all.txt
+        # output a diff of the generated list csv.txt and cts_all.txt
+        diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
         exit $exitcode
