Fix dpc++ version logic; comment-out list/diff script

diff --git a/.github/actions/run_sycl_cts/action.yml b/.github/actions/run_sycl_cts/action.yml
--- a/.github/actions/run_sycl_cts/action.yml
+++ b/.github/actions/run_sycl_cts/action.yml
@@ -76,7 +76,7 @@ runs:
         export ONEAPI_DEVICE_SELECTOR=opencl:0
         export CTS_CSV_FILE=$GITHUB_WORKSPACE/.github/scripts/sycl-cts.csv # can't set in env:
         # TODO: assume sycl-cts.csv is a new file?
-        #       SYCL-CTS/lib does not exist
+        #       SYCL-CTS/lib does not exist?
         set -x
         python $GITHUB_WORKSPACE/scripts/testing/run_cities.py \
           --color=always \
@@ -91,8 +91,9 @@ runs:
           -r SYCL-CTS/cts.xml \
           -v \
           $SYCL_CTS_FILTER || exitcode=$?
-        export OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so
-        $GITHUB_WORKSPACE/.github/scripts/create_sycl_cts_test_lists.sh $PREPEND_PATH SYCL-CTS $CTS_CSV_FILE csv.txt cts_all.txt
-        # output a diff of the generated list csv.txt and cts_all.txt
-        diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
+        # TODO: Restore the following shell script - appears to need runs including ALL test categories
+        #export OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so
+        #$GITHUB_WORKSPACE/.github/scripts/create_sycl_cts_test_lists.sh $PREPEND_PATH SYCL-CTS $CTS_CSV_FILE csv.txt cts_all.txt
+        ## output a diff of the generated list csv.txt and cts_all.txt
+        #diff csv.txt cts_all.txt || echo "WARNING - Missing some tests from sycl cts file based on test_all --list-tests - see > above"
         exit $exitcode
