flip back to cache create; add new cache handling

diff --git a/.github/actions/do_build_opencl_cts/action.yml b/.github/actions/do_build_opencl_cts/action.yml
--- a/.github/actions/do_build_opencl_cts/action.yml
+++ b/.github/actions/do_build_opencl_cts/action.yml
@@ -86,10 +86,24 @@ runs:
         retention-days: 7
         needs_tar: 'true'
 
-    - name: update opencl cts artifact cache
+    - name: check existence of opencl cts artifact cache
       if: inputs.cache_update == 'true'
+      uses: actions/cache/restore@v4
+      id: cache_check
+      with:
+        key: opencl_cts_${{inputs.target}}
+        path: build/test_conformance
+        lookup-only: true
+
+    - name: error on attempt to overwrite existing opencl cts artifact cache
+      if: inputs.cache_update == 'true' && steps.cache_check.outputs.cache-hit == 'true'
+      run: |
+        echo "Error: attempt to overwrite existing opencl cts cache: opencl_cts_${{inputs.target}}"
+        exit 1
+
+    - name: create opencl cts artifact cache
+      if: inputs.cache_update == 'true' && steps.cache_check.outputs.cache-hit != 'true'
       uses: actions/cache/save@v4
-      id: cache
       with:
         key: opencl_cts_${{inputs.target}}
         path: build/test_conformance
